// Generated by Claude; adapted by H.Ryu

#include <stdint.h>

/* Symbols defined by the linker script (mspm0c1104.ld) */
extern uint32_t _sidata;  /* start of .data initial values in FLASH */
extern uint32_t _sdata;   /* start of .data in SRAM */
extern uint32_t _edata;   /* end of .data in SRAM */
extern uint32_t _sbss;    /* start of .bss in SRAM */
extern uint32_t _ebss;    /* end of .bss in SRAM */
extern uint32_t _estack;  /* top of stack (end of SRAM) */

int main(void);

/* Default handler for unimplemented interrupts: halts execution.
   Marked weak+alias so any handler can be overridden by redefining it. */
static void default_handler(void)
{
    for (;;) {
    }
}

void Reset_Handler(void);
void NMI_Handler(void)       __attribute__((weak, alias("default_handler")));
void HardFault_Handler(void) __attribute__((weak, alias("default_handler")));
void SVC_Handler(void)       __attribute__((weak, alias("default_handler")));
void PendSV_Handler(void)    __attribute__((weak, alias("default_handler")));
void SysTick_Handler(void)   __attribute__((weak, alias("default_handler")));

/* Interrupt vector table — must be placed at the very start of FLASH.
   ARM Cortex-M hardware reads [0] for the initial stack pointer
   and [1] for the reset entry point on every reset.
   Ref: MSPM0 C-series Microcontroller TRM, page 214. */
__attribute__((section(".isr_vector")))
void (*const vector_table[])(void) = {
    (void (*)(void))(&_estack),  /* [0]  initial stack pointer */
    Reset_Handler,               /* [1]  reset handler */
    NMI_Handler,                 /* [2]  non-maskable interrupt */
    HardFault_Handler,           /* [3]  hard fault */
    0,                           /* [4]  reserved */
    0,                           /* [5]  reserved */
    0,                           /* [6]  reserved */
    0,                           /* [7]  reserved */
    0,                           /* [8]  reserved */
    0,                           /* [9]  reserved */
    0,                           /* [10] reserved */
    SVC_Handler,                 /* [11] supervisor call */
    0,                           /* [12] reserved */
    0,                           /* [13] reserved */
    PendSV_Handler,              /* [14] pendable service call */
    SysTick_Handler,             /* [15] system tick timer */
};

/* Reset_Handler: sets up the C runtime environment, then calls main().
   Runs before any C code — no initialized globals or zeroed BSS yet. */
void Reset_Handler(void)
{
    /* Copy .data initial values from FLASH to SRAM */
    uint32_t *src = &_sidata;
    uint32_t *dst = &_sdata;

    while (dst < &_edata) {
        *dst++ = *src++;
    }

    /* Zero-initialize .bss (C standard requires this) */
    dst = &_sbss;
    while (dst < &_ebss) {
        *dst++ = 0u;
    }

    /* C environment is ready — jump to application */
    (void)main();

    /* Halt if main() ever returns */
    for (;;) {
    }
}
